import { Platform } from 'react-native';
import * as FileSystem from 'expo-file-system';

// Camera-captured photos live in the OS cache directory (expo-camera default)
// until they're saved as an observation, at which point the OS is free to
// evict them at any time — a saved observation's photo could silently break.
// This copies the photo into the app's persistent document directory only at
// save time (never for demo/discarded scans, to avoid wasting storage).
//
// Web has no durable/cache distinction worth copying between (no
// FileSystem.documentDirectory), so this is a native-only concern and is a
// no-op there — the original URI is returned unchanged.
const OBSERVATIONS_DIR = FileSystem.documentDirectory
  ? `${FileSystem.documentDirectory}observations/`
  : null;

// A save button can be tapped twice while the first filesystem copy is still
// pending. Reuse the same in-flight copy for the same camera URI so both calls
// resolve to one durable URI instead of creating two files. A second tap can
// also already be queued when the first copy finishes, so keep a short-lived
// cache of completed copies as well. The store treats one durable photo as one
// observation, giving us defence in depth against double-save / double-XP.
const inFlightCopies = new Map<string, Promise<string>>();
const recentCopies = new Map<string, { uri: string; expiresAt: number }>();
const RECENT_COPY_TTL_MS = 10_000;

// Two different photos can be persisted concurrently on the very first save.
// Share directory initialisation as well so both callers cannot race through
// getInfo(false) and try to create the same directory simultaneously.
let ensureDirPromise: Promise<void> | null = null;

const SAFE_IMAGE_EXTENSIONS = new Set(['jpg', 'jpeg', 'png', 'heic', 'heif', 'webp']);
const MANAGED_PHOTO_NAME = /^\d+_[a-z0-9]{1,16}\.(?:jpg|jpeg|png|heic|heif|webp)$/i;

async function ensureObservationsDir(): Promise<void> {
  if (!OBSERVATIONS_DIR) return;
  if (ensureDirPromise) return ensureDirPromise;

  const operation = (async () => {
    const info = await FileSystem.getInfoAsync(OBSERVATIONS_DIR);
    if (!info.exists) {
      await FileSystem.makeDirectoryAsync(OBSERVATIONS_DIR, { intermediates: true });
    }
  })();

  ensureDirPromise = operation;
  try {
    await operation;
  } finally {
    if (ensureDirPromise === operation) ensureDirPromise = null;
  }
}

function imageExtension(uri: string): string {
  const withoutQuery = uri.split(/[?#]/, 1)[0];
  const match = withoutQuery.match(/\.([a-zA-Z0-9]+)$/);
  const ext = match?.[1]?.toLowerCase();
  return ext && SAFE_IMAGE_EXTENSIONS.has(ext) ? ext : 'jpg';
}

function pruneRecentCopies(now: number): void {
  for (const [sourceUri, cached] of recentCopies) {
    if (cached.expiresAt <= now) recentCopies.delete(sourceUri);
  }
}

function isManagedObservationPhoto(uri: string): boolean {
  if (!OBSERVATIONS_DIR || !uri.startsWith(OBSERVATIONS_DIR)) return false;
  // Only direct children with the filename shape generated by this module may
  // be deleted. A startsWith-only check would still accept e.g. `../other.jpg`
  // after the managed directory prefix and could escape the directory if a
  // persisted URI were corrupted or tampered with.
  const fileName = uri.slice(OBSERVATIONS_DIR.length);
  return MANAGED_PHOTO_NAME.test(fileName);
}

async function copyToDurableStorage(cacheUri: string): Promise<string> {
  try {
    await ensureObservationsDir();
    const ext = imageExtension(cacheUri);
    const randomPart = Math.random().toString(36).slice(2, 8).padEnd(6, '0');
    const destUri = `${OBSERVATIONS_DIR}${Date.now()}_${randomPart}.${ext}`;
    await FileSystem.copyAsync({ from: cacheUri, to: destUri });
    return destUri;
  } catch (err) {
    console.warn('[observationPhotoStorage] copy failed, keeping cache URI:', err);
    return cacheUri;
  }
}

/**
 * Copy a captured photo into persistent storage and return the durable URI.
 * Returns the original URI unchanged on web or on any copy failure — a
 * missing durable copy should never block saving the observation itself.
 * Concurrent and immediately-repeated calls for the same source URI share the
 * same result so a queued second tap cannot create another durable file.
 */
export async function persistObservationPhoto(cacheUri: string): Promise<string> {
  if (Platform.OS === 'web' || !OBSERVATIONS_DIR) return cacheUri;

  const now = Date.now();
  pruneRecentCopies(now);
  const recent = recentCopies.get(cacheUri);
  if (recent) return recent.uri;

  const existing = inFlightCopies.get(cacheUri);
  if (existing) return existing;

  const copyPromise = copyToDurableStorage(cacheUri);
  inFlightCopies.set(cacheUri, copyPromise);
  try {
    const uri = await copyPromise;
    recentCopies.set(cacheUri, { uri, expiresAt: Date.now() + RECENT_COPY_TTL_MS });
    return uri;
  } finally {
    if (inFlightCopies.get(cacheUri) === copyPromise) {
      inFlightCopies.delete(cacheUri);
    }
  }
}

/**
 * Delete one photo managed by this module. Arbitrary file URIs are ignored so
 * a corrupted persisted value can never make the app delete an unrelated file.
 */
export async function deleteObservationPhoto(uri?: string): Promise<void> {
  if (
    Platform.OS === 'web' ||
    !uri ||
    !isManagedObservationPhoto(uri) ||
    typeof FileSystem.deleteAsync !== 'function'
  ) {
    return;
  }

  try {
    await FileSystem.deleteAsync(uri, { idempotent: true });
  } catch (err) {
    // Record deletion must not be blocked by a stale/missing file.
    console.warn('[observationPhotoStorage] delete failed:', err);
  }
}

/** Remove every durable observation photo created by this app. */
export async function clearObservationPhotos(): Promise<void> {
  inFlightCopies.clear();
  recentCopies.clear();
  ensureDirPromise = null;
  if (
    Platform.OS === 'web' ||
    !OBSERVATIONS_DIR ||
    typeof FileSystem.deleteAsync !== 'function'
  ) {
    return;
  }

  try {
    await FileSystem.deleteAsync(OBSERVATIONS_DIR, { idempotent: true });
  } catch (err) {
    // The in-memory/user-data reset should still succeed if filesystem cleanup
    // fails (e.g. an already-missing directory or transient OS error).
    console.warn('[observationPhotoStorage] clear failed:', err);
  }
}
