/**
 * Reviewed staging snapshot from the first live Catalogue of Life XR run.
 *
 * Source: COL 2026-09-25 XR / ChecklistBank 316441 / DOI 10.48580/dgz9s
 * Generated by GitHub Actions on 2026-10-06.
 *
 * Only entries that satisfied the conservative auto-resolution gate are
 * promoted into COL_AUTO_RESOLVED_IDS. Review-queue entries are preserved
 * separately and MUST NOT populate externalIds.col until resolved.
 */

export const COL_RESOLUTION_SOURCE = {
  provider: 'catalogue_of_life',
  releaseLabel: '2026-09-25 XR',
  issuedAt: '2026-09-25',
  datasetKey: '316441',
  checklistKey: '7ddf754f-d193-4cc9-b351-99906754a03b',
  doi: '10.48580/dgz9s',
  generatedAt: '2026-10-06T12:45:48.294Z',
} as const;

export const COL_RESOLUTION_SUMMARY = {
  autoResolve: 139,
  needsReview: 10,
  unresolved: 0,
  transportError: 0,
} as const;

export const COL_AUTO_RESOLVED_IDS: Readonly<Record<string, string>> = {
  'yaku:taxon:p001': '54VX8',
  'yaku:taxon:p002': 'GWSX',
  'yaku:taxon:p003': '3MR6R',
  'yaku:taxon:p004': '6VNZC',
  'yaku:taxon:p005': '6FYFR',
  'yaku:taxon:p007': '65XF6',
  'yaku:taxon:p008': '48X8B',
  'yaku:taxon:p010': 'G4RP',
  'yaku:taxon:p011': '4FCZN',
  'yaku:taxon:p012': '4PTWY',
  'yaku:taxon:p013': '6TBX6',
  'yaku:taxon:p014': '3BFFS',
  'yaku:taxon:p015': '322XL',
  'yaku:taxon:p016': 'QT37',
  'yaku:taxon:p017': '4ZRH7',
  'yaku:taxon:p018': '76TV9',
  'yaku:taxon:p019': '793ZB',
  'yaku:taxon:p020': '9ZVG',
  'yaku:taxon:p021': '4JPWP',
  'yaku:taxon:p022': '6XHX7',
  'yaku:taxon:p023': '6NW79',
  'yaku:taxon:p024': '9GDM',
  'yaku:taxon:p025': 'XYLW',
  'yaku:taxon:p026': '4M2DF',
  'yaku:taxon:p027': 'HR8K',
  'yaku:taxon:p028': '4TPQL',
  'yaku:taxon:p029': '7FSGR',
  'yaku:taxon:p030': 'VJ33',
  'yaku:taxon:p031': '3FV9H',
  'yaku:taxon:p032': '53JT3',
  'yaku:taxon:p033': '4TPGJ',
  'yaku:taxon:p034': '3KKX8',
  'yaku:taxon:p035': '6H23S',
  'yaku:taxon:p036': '4VVPH',
  'yaku:taxon:p037': 'VB5S',
  'yaku:taxon:p038': '6S4MX',
  'yaku:taxon:p039': 'WX9R',
  'yaku:taxon:p040': '65WWJ',
  'yaku:taxon:p041': '3MQVD',
  'yaku:taxon:p043': '34B6N',
  'yaku:taxon:p044': 'G4SD',
  'yaku:taxon:p045': '3YF7H',
  'yaku:taxon:p048': 'YP9C',
  'yaku:taxon:p049': '4RHRJ',
  'yaku:taxon:p050': '4HM9F',
  'yaku:taxon:p051': 'GNBK',
  'yaku:taxon:p052': 'BDYW',
  'yaku:taxon:p053': 'XFFY',
  'yaku:taxon:p054': '6VLK4',
  'yaku:taxon:p055': '5BH4P',
  'yaku:taxon:p057': '3S2DF',
  'yaku:taxon:p058': '4Y9CR',
  'yaku:taxon:p059': '33DCV',
  'yaku:taxon:p061': 'BDN5',
  'yaku:taxon:p062': '9KCTL',
  'yaku:taxon:p063': 'W47Q',
  'yaku:taxon:p064': '67W3X',
  'yaku:taxon:p065': 'XP6T',
  'yaku:taxon:p066': '3WZNV',
  'yaku:taxon:p067': '6Y3NV',
  'yaku:taxon:p069': '5CSG8',
  'yaku:taxon:p070': '48Y89',
  'yaku:taxon:p071': '6B3F3',
  'yaku:taxon:p072': '4768L',
  'yaku:taxon:p073': '57LJT',
  'yaku:taxon:p074': '5C2HC',
  'yaku:taxon:p075': '6PRGN',
  'yaku:taxon:p076': '43MQZ',
  'yaku:taxon:p078': '6TTM9',
  'yaku:taxon:p079': '6H9YH',
  'yaku:taxon:h001': '6P3VZ',
  'yaku:taxon:h002': '8X58V',
  'yaku:taxon:h003': '56RHL',
  'yaku:taxon:h004': '48GBK',
  'yaku:taxon:h005': '72ZGR',
  'yaku:taxon:h006': '72V3R',
  'yaku:taxon:h007': '6XH46',
  'yaku:taxon:h008': '6T7B5',
  'yaku:taxon:h009': '6JBPX',
  'yaku:taxon:h010': 'DY93',
  'yaku:taxon:h011': '6B3DT',
  'yaku:taxon:h012': '32K27',
  'yaku:taxon:h013': '5Z6SQ',
  'yaku:taxon:h014': '6F4H8',
  'yaku:taxon:h015': '545PT',
  'yaku:taxon:h016': '3PGNT',
  'yaku:taxon:h017': 'ZL2V',
  'yaku:taxon:h018': '7FGVJ',
  'yaku:taxon:h019': '6C76X',
  'yaku:taxon:h020': '6V8D2',
  'yaku:taxon:h021': '5VHVT',
  'yaku:taxon:h022': 'GW9Y',
  'yaku:taxon:h023': 'HB44',
  'yaku:taxon:h024': '6DW3C',
  'yaku:taxon:h025': '79HX3',
  'yaku:taxon:h026': '5D5GX',
  'yaku:taxon:h027': '6697C',
  'yaku:taxon:h028': '74TMF',
  'yaku:taxon:h029': '5TX7G',
  'yaku:taxon:h030': '4HWV3',
  'yaku:taxon:h031': 'RHGC',
  'yaku:taxon:h032': '6C25L',
  'yaku:taxon:h033': '3ZJGV',
  'yaku:taxon:h034': '459NC',
  'yaku:taxon:h035': 'QT4R',
  'yaku:taxon:h036': 'N7ZK',
  'yaku:taxon:h037': '5D5G7',
  'yaku:taxon:h038': '6HJ7Q',
  'yaku:taxon:h039': '66QSL',
  'yaku:taxon:h040': '67S22',
  'yaku:taxon:h041': '6B2TC',
  'yaku:taxon:h042': '44FPX',
  'yaku:taxon:h043': 'VMNQ',
  'yaku:taxon:h044': '5CWNG',
  'yaku:taxon:h045': '7F2CH',
  'yaku:taxon:h046': 'MJ92',
  'yaku:taxon:h048': '58R6D',
  'yaku:taxon:h049': '4J4Z3',
  'yaku:taxon:h050': '6VJPT',
  'yaku:taxon:h051': '52H37',
  'yaku:taxon:h052': 'PJDZ',
  'yaku:taxon:h053': 'C5RS',
  'yaku:taxon:h054': 'V857',
  'yaku:taxon:h055': '6NGH4',
  'yaku:taxon:h056': '4WYTB',
  'yaku:taxon:h057': '5VYFN',
  'yaku:taxon:h058': 'C6ZV',
  'yaku:taxon:h059': '6N77Y',
  'yaku:taxon:h060': '4DYHZ',
  'yaku:taxon:h061': '3K6TW',
  'yaku:taxon:h062': '3F66X',
  'yaku:taxon:h063': '6S5ZD',
  'yaku:taxon:h064': 'FNGV',
  'yaku:taxon:h065': 'GSV4',
  'yaku:taxon:h066': '4F9T2',
  'yaku:taxon:h067': '9TGX',
  'yaku:taxon:h068': '4WP77',
  'yaku:taxon:h069': 'W9KM',
  'yaku:taxon:h071': '6QN36',
};

export interface ColReviewCandidate {
  colId: string;
  scientificName: string;
  canonicalName: string;
  rank: string;
  status: string;
  confidence: number;
  acceptedTaxon?: {
    providerRecordId: string;
    scientificName: string;
    canonicalName?: string;
    rank?: string;
    status?: string;
  };
}

export interface ColReviewQueueEntry {
  taxonId: string;
  inputScientificName: string;
  reasons: string[];
  candidate: ColReviewCandidate;
}

export const COL_REVIEW_QUEUE: readonly ColReviewQueueEntry[] = [
  {
    taxonId: 'yaku:taxon:p006',
    inputScientificName: 'Pueraria lobata',
    reasons: ['status_synonym'],
    candidate: {
      colId: '4QFVR',
      scientificName: 'Pueraria lobata (Willd.) Ohwi',
      canonicalName: 'Pueraria lobata',
      rank: 'SPECIES',
      status: 'synonym',
      confidence: 99,
      acceptedTaxon: {
        providerRecordId: 'CGCLG',
        scientificName:
          'Pueraria montana var. lobata (Willd.) Maesen & S.M.Almeida ex Sanjappa & Predeep',
        canonicalName: 'Pueraria montana lobata',
        rank: 'VARIETY',
        status: 'unknown',
      },
    },
  },
  {
    taxonId: 'yaku:taxon:p042',
    inputScientificName: 'Veratrum album subsp. oxysepalum',
    reasons: ['rank_mismatch', 'status_synonym', 'confidence_below_auto_threshold'],
    candidate: {
      colId: '5LQPG',
      scientificName: 'Veratrum album subsp. oxysepalum (Turcz.) Hultén',
      canonicalName: 'Veratrum album oxysepalum',
      rank: 'SUBSPECIES',
      status: 'synonym',
      confidence: 84,
      acceptedTaxon: {
        providerRecordId: '7FNJV',
        scientificName: 'Veratrum oxysepalum Turcz.',
        canonicalName: 'Veratrum oxysepalum',
        rank: 'SPECIES',
        status: 'unknown',
      },
    },
  },
  {
    taxonId: 'yaku:taxon:p046',
    inputScientificName: 'Elatostema umbellatum var. majus',
    reasons: ['rank_mismatch', 'status_synonym', 'confidence_below_auto_threshold'],
    candidate: {
      colId: '5NPQZ',
      scientificName: 'Elatostema umbellatum var. majus Maxim.',
      canonicalName: 'Elatostema umbellatum majus',
      rank: 'VARIETY',
      status: 'synonym',
      confidence: 88,
      acceptedTaxon: {
        providerRecordId: '6F363',
        scientificName: 'Elatostema involucratum Franch. & Sav.',
        canonicalName: 'Elatostema involucratum',
        rank: 'SPECIES',
        status: 'unknown',
      },
    },
  },
  {
    taxonId: 'yaku:taxon:p047',
    inputScientificName: 'Glechoma hederacea var. grandis',
    reasons: ['rank_mismatch', 'status_synonym', 'confidence_below_auto_threshold'],
    candidate: {
      colId: '5HH3P',
      scientificName: 'Glechoma hederacea subsp. grandis (A.Gray) H.Hara',
      canonicalName: 'Glechoma hederacea grandis',
      rank: 'SUBSPECIES',
      status: 'synonym',
      confidence: 84,
      acceptedTaxon: {
        providerRecordId: '3G6WD',
        scientificName: 'Glechoma grandis (A.Gray) Kuprian.',
        canonicalName: 'Glechoma grandis',
        rank: 'SPECIES',
        status: 'unknown',
      },
    },
  },
  {
    taxonId: 'yaku:taxon:p056',
    inputScientificName: 'Hemerocallis fulva var. angustifolia',
    reasons: ['rank_mismatch', 'confidence_below_auto_threshold'],
    candidate: {
      colId: '7M4GJ',
      scientificName: 'Hemerocallis fulva var. angustifolia Baker',
      canonicalName: 'Hemerocallis fulva angustifolia',
      rank: 'VARIETY',
      status: 'accepted',
      confidence: 88,
    },
  },
  {
    taxonId: 'yaku:taxon:p060',
    inputScientificName: 'Calystegia japonica',
    reasons: ['status_synonym'],
    candidate: {
      colId: 'Q7ZV',
      scientificName: 'Calystegia japonica (Thunb.) Choisy',
      canonicalName: 'Calystegia japonica',
      rank: 'SPECIES',
      status: 'synonym',
      confidence: 99,
      acceptedTaxon: {
        providerRecordId: '5ZXL6',
        scientificName: 'Convolvulus japonicus Thunb.',
        canonicalName: 'Convolvulus japonicus',
        rank: 'SPECIES',
        status: 'unknown',
      },
    },
  },
  {
    taxonId: 'yaku:taxon:p068',
    inputScientificName: 'Lapsana apogonoides',
    reasons: ['status_synonym'],
    candidate: {
      colId: '3S9WQ',
      scientificName: 'Lapsana apogonoides Maxim.',
      canonicalName: 'Lapsana apogonoides',
      rank: 'SPECIES',
      status: 'synonym',
      confidence: 100,
      acceptedTaxon: {
        providerRecordId: '3S9Y6',
        scientificName: 'Lapsanastrum apogonoides (Maxim.) Pak & K.Bremer',
        canonicalName: 'Lapsanastrum apogonoides',
        rank: 'SPECIES',
        status: 'unknown',
      },
    },
  },
  {
    taxonId: 'yaku:taxon:p077',
    inputScientificName: 'Dianthus superbus var. longicalycinus',
    reasons: ['rank_mismatch', 'status_synonym', 'confidence_below_auto_threshold'],
    candidate: {
      colId: '5GVMQ',
      scientificName: 'Dianthus superbus subsp. longicalycinus (Maxim.) Kitam.',
      canonicalName: 'Dianthus superbus longicalycinus',
      rank: 'SUBSPECIES',
      status: 'synonym',
      confidence: 84,
      acceptedTaxon: {
        providerRecordId: '6CPSD',
        scientificName: 'Dianthus longicalyx Miq.',
        canonicalName: 'Dianthus longicalyx',
        rank: 'SPECIES',
        status: 'unknown',
      },
    },
  },
  {
    taxonId: 'yaku:taxon:h047',
    inputScientificName: 'Hyssopus officinalis',
    reasons: ['status_synonym'],
    candidate: {
      colId: '6MT5F',
      scientificName: 'Hyssopus officinalis L.',
      canonicalName: 'Hyssopus officinalis',
      rank: 'SPECIES',
      status: 'synonym',
      confidence: 100,
      acceptedTaxon: {
        providerRecordId: 'CD7P2',
        scientificName: 'Dracocephalum officinale subsp. officinale',
        canonicalName: 'Dracocephalum officinale officinale',
        rank: 'SUBSPECIES',
        status: 'unknown',
      },
    },
  },
  {
    taxonId: 'yaku:taxon:h070',
    inputScientificName: 'Hibiscus sabdariffa',
    reasons: ['status_synonym'],
    candidate: {
      colId: '3LK87',
      scientificName: 'Hibiscus sabdariffa L.',
      canonicalName: 'Hibiscus sabdariffa',
      rank: 'SPECIES',
      status: 'synonym',
      confidence: 100,
      acceptedTaxon: {
        providerRecordId: 'KZJLJ',
        scientificName:
          'Sabdariffa gossypiifolia (Mill.) M.M.Hanes & R.L.Barrett',
        canonicalName: 'Sabdariffa gossypiifolia',
        rank: 'SPECIES',
        status: 'unknown',
      },
    },
  },
];

export const COL_REVIEW_TAXON_IDS = new Set(
  COL_REVIEW_QUEUE.map((entry) => entry.taxonId),
);
